INSERT INTO movie_character VALUES(1, 'Rick', 'ALIVE', 'MALE', 1);
INSERT INTO movie_character VALUES(2, 'Rick Sanchez', 'ALIVE', 'MALE', 2);
INSERT INTO movie_character VALUES(3, 'Rick NOTSanchez', 'ALIVE', 'MALE', 3);
INSERT INTO movie_character VALUES(4, 'Morty', 'ALIVE', 'MALE', 4);
INSERT INTO movie_character VALUES(5, 'Summer', 'ALIVE', 'FEMALE', 5);
INSERT INTO movie_character VALUES(6, 'Evil Morty', 'ALIVE', 'MALE', 6);
INSERT INTO movie_character VALUES(7, 'Doctor House', 'ALIVE', 'MALE', 7);
INSERT INTO movie_character VALUES(8, 'Snake', 'UNKNOWN', 'UNKNOWN', 8);
INSERT INTO movie_character VALUES(9, 'Bob', 'ALIVE', 'MALE', 9);
INSERT INTO movie_character VALUES(10, 'Pickle Rick', 'ALIVE', 'MALE', 10);